import Head from "next/head";
import Image from "next/image";
import Header from "./header/header";
import Footer from "./footer/footer";

const meLoader = ({ src, width, quality }: any) => {
  return `https://i.ibb.co/sy8TNsM/card.jpg${src}?w=${width}&q=${
    quality || 75
  }`;
};

const Home = () => {
  return (
    <div className="min-h-screen px-4 flex flex-col justify-center h-screen bg-gradient-to-r from-gray-500 to-black">
      <Head>
        <title>1000VIA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center ">
        <Header />
        <h1 className="font-bold text-4xl text-white m-4 ">
          Milvia Alvarez Zabala
        </h1>
        <span className="text-3xl m-4">💻</span>
        <span className="text-2xl text-gray-400 m-4">
          Desarrolladora javascript
        </span>
        <section className="w-full h-full flex items-center justify-center">
          <Image
            src="https://i.ibb.co/sy8TNsM/card.jpg"
            alt="This is me"
            width={401}
            height={401}
            loader={meLoader}
            className="rounded-3xl"
          />
        </section>
      </main>
      <Footer />
    </div>
  );
};
export default Home;
